services:
  postgres:
    image: postgres
    restart: always
    environment:
        POSTGRES_PASSWORD: productpw
    ports:
        - 5522:5432 
    volumes:
        -  pgdata:/var/lib/postgresql/data
  mongo:
    image: mongo
    restart: always
    environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: mongopw
    ports:
        - 27070:27017
    volumes:
        - mongodata:/var/lib/mongodb/data

  adminer:
    image: adminer
    restart: always
    ports:
        - 8080:8080
volumes:
    pgdata:
    mongodata:
